#! /bin/bash
if [ $# -lt 1 ]; then echo usage: rcasm war.red; exit; fi
tmp=$(tempfile)
grep "^;" $1 > $tmp
echo ";assert 1" >> $tmp
pmars-server -r 0 $1 | sed '1,2d' >> $tmp
mv $tmp $(echo $1 | awk '{ gsub (".red$", ""); print }').rc
